version: "3"

services:
  fake-prusa:
    container_name: fake_prusa
    build:
      context: fake_prusa_api/
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5000:5000/tcp" # you can restrict it to specific IP address if you want
    environment:
      TZ: 'UTC/Etc'
    restart: unless-stopped

  fake-esp32camera:
    container_name: fake_esp32camera
    build:
      context: fake_camera/
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8888:8888/tcp" # you can restrict it to specific IP address if you want
    environment:
      TZ: 'UTC/Etc'
    restart: unless-stopped

  node-red:
    container_name: nodered
    image: nodered/node-red
    build:
      context: node-red/
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:1880:1880/tcp" # you can restrict it to specific IP address if you want
    environment:
      TZ: 'UTC/Etc'
    volumes:
      - "./node-red/data:/data:rw"
    restart: unless-stopped

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - "0.0.0.0:1883:1883/tcp" # you can restrict it to specific IP address if you want
      - "0.0.0.0:9001:9001/tcp" # websoket
    environment:
      TZ: 'UTC/Etc'
    volumes:
      - "./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw"
      - "./mqtt/data:/mosquitto/data:rw"
      - "./mqtt/log:/mosquitto/log:rw"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 30s
      timeout: 10s
      retries: 3

  esphome:
    container_name: esphome
    image: esphome/esphome:2023.10
    # network_mode: host # uncomment to actually run on the host network and would be able to discover certain devices
    ports:
      - "6052:6052/tcp"
    environment:
      TZ: 'UTC/Etc'
    volumes:
      - "./esphome:/config:rw"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--max-time", "5", "--no-keepalive", "--fail", "--write-out", "'\n'", "http://0.0.0.0:6052/version"]
      interval: 30s
      timeout: 10s
      retries: 3
